title: Angela Odermatt
description: Personal Website

url: https://long-haul.netlify.app
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: Research
      url: /research
    - title: CV
      url: /cv

social:
    github: angelaodermatt
    email: angela.odermatt@princeton.edu
    linkedin: www.linkedin.com/in/angela-odermatt-0843021b6

google_analytics: "UA-58263416-1"

disqus:
    shortname: angelaodermatt
